name: casp
channels:
  - conda-forge
  - defaults
dependencies:
  - _python_abi3_support=1.0=hd8ed1ab_2
  - appnope=0.1.4=pyhd8ed1ab_1
  - asttokens=3.0.0=pyhd8ed1ab_1
  - black=25.1.0=pyh866005b_0
  - bzip2=1.0.8=hd037594_8
  - ca-certificates=2025.10.5=hbd8a1cb_0
  - click=8.3.0=pyh707e725_0
  - comm=0.2.3=pyhe01879c_0
  - cpython=3.14.0=py314hd8ed1ab_102
  - debugpy=1.8.17=py314hac9ea21_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - greenlet=3.2.4=py314he8615de_1
  - importlib-metadata=8.7.0=pyhe01879c_1
  - ipykernel=7.1.0=pyh5552912_0
  - ipython=9.6.0=pyhfa0c392_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.9.1=pyhc90fa1f_0
  - krb5=1.21.3=h237132a_0
  - libcxx=21.1.4=hf598326_0
  - libedit=3.1.20250104=pl5321hafb1f1b_0
  - libexpat=2.7.1=hec049ff_0
  - libffi=3.5.2=he5f378a_0
  - liblzma=5.8.1=h39f12f2_2
  - libmpdec=4.0.0=h5505292_0
  - libsodium=1.0.20=h99b78c6_0
  - libsqlite=3.50.4=hf8de324_0
  - libzlib=1.3.1=h8359307_2
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - mypy_extensions=1.1.0=pyha770c72_0
  - ncurses=6.5=h5e97a16_3
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - openssl=3.5.4=h5503f6c_0
  - packaging=25.0=pyh29332c3_1
  - parso=0.8.5=pyhcf101f3_0
  - pathspec=0.12.1=pyhd8ed1ab_1
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pip=25.2=pyh145f28c_0
  - platformdirs=4.5.0=pyhcf101f3_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - psutil=7.1.2=py314h9d33bd4_1
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - python=3.14.0=h40d2674_102_cp314
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-gil=3.14.0=h4df99d1_102
  - python_abi=3.14=8_cp314
  - pyzmq=27.1.0=py312hd65ceae_0
  - readline=8.2=h1d1bf99_2
  - six=1.17.0=pyhe01879c_1
  - sqlalchemy=2.0.44=py314h0612a62_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - tk=8.6.13=h892fb3f_2
  - tornado=6.5.2=py314hb84d1df_1
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing-extensions=4.15.0=h396c80c_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025b=h78e105d_0
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - zeromq=4.3.5=h888dc83_9
  - zipp=3.23.0=pyhd8ed1ab_0
  - zstd=1.5.7=h6491c7d_2
prefix: /Users/shan/miniconda3/envs/casp
