# Top-level section for database settings
database:
  # type can be 'sqlite', 'mssql', or 'duckdb'
  type: 'sqlite3' # <--- CHANGED

  # Specific settings for sqlite
  sqlite3:
    db_location: './caspary.sqlite3' # Changed to default
    in_memory: false

  # Specific settings for mssql
  # mssql:
  #   server_name: 'YOUR_SERVER_NAME'
  #   db_name: 'YOUR_DATABASE_NAME'
  #   driver: '{ODBC Driver 17 for SQL Server}'
  #   trusted_connection: 'yes'

  # Specific settings for duckdb  <--- ADDED
  # duckdb:
  #   db_location: './caspary.duckdb' # Set to match your main script
  #   in_memory: false

# Top-level section for logging
logging:
  level: "INFO"                 # Default level (DEBUG, INFO, WARNING, ERROR, CRITICAL)
  log_to_file: true             # Whether to write to a file
  log_file: "scan_job.log"      # The file to write to
  rotation_size_mb: 10          # Rotate log file after it reaches 10MB
  rotation_backup_count: 5      # Keep 5 old log files
  # Format for the log messages
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"